version: '3'

services:
  project-egingerz-web:
    container_name: project-egingerz-web
    image: nginx:alpine
    depends_on:
      # `app`Because the service (container) needs to be started first`depends_on`Is specified
      - project-egingerz-app
    ports:
      #Port mapping:"Host OS port:container(Nginx)Port"
      - "7080:80"
    volumes:
      #volume mount:"Host OS path:Path in the container"
      - ./web/conf.d:/etc/nginx/conf.d
    #networks:
    #  - nginx_network

  project-egingerz-app:
    container_name: project-egingerz-app
    image: project-egingerz-app #Specify the name of the Docker image to be built
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
    #networks:
    #  - nginx_network
    #For example, if you want to edit the source code in real time`volumes`Convenient to mount with
    # volumes:
    #   - ./app/app:/app/app
    #of the app container`CMD`To overwrite`command`use
    # command: "uvicorn app.main:app --reload --host 0.0.0.0"

  project-egingerz-db:
    container_name: project-egingerz-db
    #image: mysql:8.0
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'egingerz'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    #command: --default-authentication-plugin=mysql_native_password # for 8.0
    ports:
      - 33305:3306

#networks:
#  nginx_network:
#    driver: bridge
networks:
  default:
    external:
      name: https-portal

volumes:
  mysql_data: