[tool.poetry]
name = "project_egingerz_app"
version = "0.1.0"
description = "just for Eginger Z"
authors = ["Your Name <crazymamecan@to48.org>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "*"
fastapi = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"